services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    user: elasticsearch
    command: >
      /bin/sh -c "./bin/elasticsearch-plugin install
      file:///serbian-analyzer/serbian-analyzer.zip;
      /usr/local/bin/docker-entrypoint.sh"
    environment:
      - discovery.type=single-node
      - node.name=udd
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic
    volumes:
      - ./serbian-analyzer:/serbian-analyzer

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash:7.4.0
    networks:
      - elastic

networks:
  elastic: null
